language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS phonebook;'
  - mysql -u root -e "CREATE USER 'user'@'localhost' IDENTIFIED BY 'user';"
  - mysql -u root -e "GRANT ALL ON phonebook.* TO 'user'@'localhost';"

notifications:
  email: false
