language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS \`phonebook\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -uroot -e "CREATE USER user@localhost IDENTIFIED BY 'password';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON \`phonebook\`.* TO user@localhost IDENTIFIED BY 'password';"

notifications:
  email: false
