language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS phonebook;'
  - mysql -e 'grant all privileges on database phonebook to "root@localhost"'

notifications:
  email: false
