language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS \`contact_manager\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -uroot -e "CREATE USER user@localhost IDENTIFIED BY 'password';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON \`contact_manager\`.* TO user@localhost IDENTIFIED BY 'password';"

branches:
  only:
  - master

#notifications:
#  email: false

#env:
#  - PB_ROOT=$TRAVIS_BUILD_DIR
